/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCard: typeof import('./src/components/ActivityCard.vue')['default']
    CharacterLabel: typeof import('./src/components/character/CharacterLabel.vue')['default']
    CharacterTag: typeof import('./src/components/character/CharacterTag.vue')['default']
    DailyCard: typeof import('./src/components/countdown/DailyCard.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    LiveCard: typeof import('./src/components/countdown/LiveCard.vue')['default']
    NosanCard: typeof import('./src/components/activity/NosanCard.vue')['default']
    PoolCard: typeof import('./src/components/activity/PoolCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidestoryCard: typeof import('./src/components/activity/SidestoryCard.vue')['default']
  }
}
